#!/usr/bin/env python3
# @python3
# @author sabot <sabot@inuits.eu>
"""Manage a dictionary of directory alias/path pairs"""
import sys
import os
import json
import click

__VERSION__ = '0.0.2'

# 3 params are needed for click callback
def show_version(ctx, param, value):
    """Print version information and exit."""
    if not value:
        return
    click.echo('Goto %s' % __VERSION__)
    ctx.exit() # quit the program

def list_entries(dictionary):
     for key in dictionary:
         print("{0:15}:{1}".format(key,dictionary[key]))

def add_entry(dictionary, filepath, path, alias, silent=False):
    """Add a new path alias and dump the dictionary to json"""

    path = os.path.abspath(path) # get absolute path to target
    if not silent:
        print("Adding alias {} for path {} ".format(alias,path))
    dictionary[alias] = path

    try:
        jsondata = json.dumps(dictionary, sort_keys=True)
        fd = open(filepath, 'w')
        fd.write(jsondata)
        fd.close()
    except Exception as e:
        print('Error writing to dictionary file: ', str(e))
        pass

def get_entries(filename):
    """Load the json alias entries"""
    returndata = {}
    if os.path.exists(filename) and os.path.getsize(filename) > 0:
        try:
            fd = open(filename, 'r')
            entries = fd.read()
            fd.close()
            returndata = json.loads(entries)

        except Exception as e:
            print('Error reading dictionary file: ', str(e))
            pass
    else:
        print('Dictionary file not found or empty - spawning new one in', filename)
        newfile = open(filename,'w')
        newfile.write('')
        newfile.close()

    return returndata

@click.command()
@click.option('--version', '-v', is_flag=True, is_eager=True,
              help='Print version information and exit.', expose_value=False,
              callback=show_version)
@click.option('--add', '-a', help="Add a new path alias")
@click.option('--target', '-t', help="Alias target path instead of the current directory")
@click.argument('alias', default='currentdir')
@click.option('--poll', '-p', help="Check if alias exists")
@click.option('--listentries', '-l', is_flag=True, help='List dictionary entries')
@click.pass_context
def g2dict(ctx, add, poll, alias, target, listentries):
    '''Manage a dictionary with directory alias/path pairs in it''' 

    # load dictionary
    filepath = os.path.join(os.getenv('HOME'), '.g2dict')
    dictionary = get_entries(filepath)
    current_dir = os.getcwd()
   
    if listentries:
        list_entries(dictionary)
        exit();
    if poll: # check if alias exists (used by shellscript)
        if poll in dictionary:
            print('True')
        else: 
            print('False')
    elif add: # add a path alias to the dictionary
        if target: # don't use current dir as target
            if not os.path.exists(target):
                print('Target path not found!')
                ctx.exit()
            else:
                add_entry(dictionary, filepath, target, add)
        else: # use current dir as target
            add_entry(dictionary, filepath, current_dir, add)

    elif alias != 'currentdir':
        if alias in dictionary:
            entry = dictionary[alias]
            add_entry(dictionary, filepath, current_dir, 'prev', True) #store directory we came from
            print(entry)

if __name__ == '__main__':
    g2dict()
